app/core/urls.py
from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views as core

app_name = 'core'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('cadastro/', core.UserCreateView.as_view(), name='cadastro'),
]

app/jogo/urls.py
from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from . import views as jogo

app_name = 'jogo'

urlpatterns = [
	path('', jogo.Home.as_view(), name='home'),
	path('partida/', jogo.NovaPartida.as_view(), name = 'partida'),
	path('pais/<pk>', jogo.Partida.as_view(), name = 'pais'),
	path('salvar/<pk>', jogo.SalvarPartida.as_view(), name = 'salvar'),
	path('finalizar/', jogo.Finalizar.as_view(), name = 'finalizar'),
	path('continuar/', jogo.Continuar.as_view(), name = 'continuar')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carmen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # core
    path('', include('app.core.urls'), name = 'core'),
    # jogo
    path('', include('app.jogo.urls'), name = 'jogo'),
]

app/core/models.py
from __future__ import unicode_literals

import uuid

from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import AbstractUser, Group, Permission


# CreateUpdateModel
# - - - - - - - - - - - - - - - - - - -
class CreateUpdateModel(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now=True)

    class Meta:
        abstract = True


# UUIDUser
# - - - - - - - - - - - - - - - - - - -
class UUIDUser(AbstractUser):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    groups = models.ManyToManyField(Group, blank=True, related_name="uuiduser_set", related_query_name="user")
    user_permissions = models.ManyToManyField(Permission, blank=True, related_name="uuiduser_set", related_query_name="user")

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

app/jogo/models.py
from django.db import models
from app.core.models import UUIDUser

class Pais(models.Model):
	nome = models.CharField(max_length = 75, verbose_name = 'Nome do País')
	descricao = models.TextField(verbose_name = 'Descrição')
	imagem_pais = models.ImageField(upload_to='paises/', verbose_name = 'Imagem do País')
	testemunha_um_nome = models.CharField(max_length = 75, verbose_name = 'Nome da Testemunha Um')
	testemunha_um_fala = models.TextField(verbose_name = 'Fala da Testemunha Um')
	testemunha_um_imagem = models.ImageField(upload_to='testemunhas/', verbose_name = 'Imagem da Testemunha Um')
	testemunha_dois_nome = models.CharField(max_length = 75, verbose_name = 'Nome da Testemunha Dois')
	testemunha_dois_fala = models.TextField(verbose_name = 'Fala da Testemunha Dois')
	testemunha_dois_imagem = models.ImageField(upload_to='testemunhas/', verbose_name = 'Imagem da Testemunha Dois')
	pais_um = models.ForeignKey('Pais', on_delete = models.CASCADE, related_name = 'paisum', verbose_name = 'País Um', blank = True, null = True)
	pais_um_imagem = models.ImageField(upload_to='paises/', verbose_name = 'Bandeira do País Um', blank = True, null = True)
	pais_dois = models.ForeignKey('Pais', on_delete = models.CASCADE, related_name = 'paisdois', verbose_name = 'País Dois', blank = True, null = True)
	pais_dois_imagem = models.ImageField(upload_to='paises/', verbose_name = 'Bandeira do País Dois', blank = True, null = True)

	def __str__(self):
		return self.nome

	class Meta:
		verbose_name = 'País'
		verbose_name_plural = 'Paises'

class Save(models.Model):
	usuario = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'user', verbose_name = 'Usuário')
	pais = models.ForeignKey(Pais, on_delete = models.CASCADE, related_name = 'pais', verbose_name = 'País')
	criado_em = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return 'Salvamento da partida do Usuário: %s' % self.usuario.username

	class Meta:
		ordering = ["criado_em"]
		verbose_name = 'Salvamento'
		verbose_name_plural = 'Salvamentos'

app/core/forms.py
from django import forms

from . import models

class RegistrationUserForm(forms.ModelForm):
  
  class Meta:
    model = models.UUIDUser
    fields = ('username', 'email', 'password')
    labels = {
    	'username': 'Nome de Usuário',
    	'email': 'E-mail',
    	'password': 'Senha',
    }
    widgets = {
      'password': forms.PasswordInput()
    }

app/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

from django.urls import reverse_lazy

from . import models

from .forms import RegistrationUserForm

class UserCreateView(CreateView):
    model = models.UUIDUser
    template_name = 'core/cadastro.html'
    success_url = reverse_lazy('core:login')
    form_class = RegistrationUserForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.set_password(obj.password)
    	obj.save()
    	return super(UserCreateView, self).form_valid(form)

app/jogo/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views import View

from django.urls import reverse_lazy
from .models import Pais, Save

class Home(View):
	def get(self, request):
		return render(request, 'jogo/start.html')

class NovaPartida(View):
	def get(self, request):
		pais = Pais.objects.filter(nome = 'Paris - França').first()
		print (pais.pk)
		return render(request, 'jogo/game.html', {'pais': pais})

class Partida(View):
	def get(self, request, pk):
		pais = Pais.objects.filter(id = pk).first()
		if pk == "6":
			return render(request, 'jogo/fim.html', {'pais': pais})	
		return render(request, 'jogo/game.html', {'pais': pais})

class SalvarPartida(View):
	def get(self, request, pk):
		pais = Pais.objects.filter(id = pk).first()
		salvar = Save(usuario = self.request.user, pais = pais)
		salvar.save()
		return redirect('jogo:home')

class Finalizar(View):
	def get(self, request):
		salvamentos = Save.objects.filter(usuario = self.request.user)
		for salvar in salvamentos:
			salvar.delete()
		return redirect('jogo:home')

class Continuar(View):
	def get(self, request):
		salvamentos = Save.objects.filter(usuario = self.request.user).order_by('-criado_em')
		if len(salvamentos) == 0:
			return render(request, 'jogo/start.html', {'mensagem': 'Desculpe, você não salvou nenhuma partida!'})
		else:
			return render(request, 'jogo/game.html', {'pais': salvamentos[0].pais})

templates/core/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>Cadastro - Carmen SanDiego</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body style="background-color: #999999;">
	
	<div class="limiter">
		<div class="container-login100">
			<div class="login100-more"></div>

			<div class="wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50">
				<form class="login100-form validate-form" method="post">
          {% csrf_token %}
					<span class="login100-form-title p-b-59">
						Cadastro de Usuário
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<span class="label-input100">Email</span>
						<input class="input100" type="text" name="email" placeholder="Email addess...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" placeholder="Username...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" name="password" placeholder="*************">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Cadastrar-se
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/core/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login - Carmen SanDiego</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title">
					<span class="login100-form-title-1">
						Login
					</span>
				</div>

				<form class="login100-form validate-form" method="post">
					{% csrf_token %}
					<div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" placeholder="Enter your username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-18" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" name="password" placeholder="Enter your password">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>

templates/jogo/fim.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Camen San Diego - França</title>
	<link href="https://fonts.googleapis.com/css?family=Aldrich|Allerta+Stencil|Bangers|Barrio|Black+Ops+One|Bungee+Shade|Diplomata|Faster+One|Holtwood+One+SC|Monofett|New+Rocker|Pacifico|Press+Start+2P|Righteous|Sigmar+One" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


<style type="text/css">
body {
	font-family: 'Press Start 2P';
}

p {
	font-family: 'Press Start 2P';
	font-size: 14px;
}

.tudo {
	display: table;
}

.border {
	border: 5px solid #fff;
}

.rigth {
	float: left;
}

.imagem-wrapper {
    width: 40%;
    height: 544px;
    overflow: hidden;
    position: relative;
    float: left;
}

.conteudo {
	margin-left: 42%;
	height: 450px;
	padding: 10px;
}

.botoes {
	margin-top: 2%;
	margin-left: 42%;
}

.imagem {
    width: 800px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translateX(-50%) translateY(-50%);
}

.btn-finalizar {
	position: absolute;
	left: 65%;
}
</style>
</head>
<body style="background-color: #141414;">
	<div style="display: inline-block;">
	<div style="color: #fff; text-align: center; font-family: 'Press Start 2P'; font-size: 11px; margin-bottom: 5px;" class="border">
		<h1>{{pais.nome}}</h1>
	</div>
	<div class="imagem-wrapper border">
		<img class="imagem" src="/media/{{pais.imagem_pais}}">
	</div>
	<div style="color: #fff; font-family: 'Press Start 2P';" class="conteudo border">
		<p>{{pais.descricao}}</p>
	</div>
	<div style="font-family: 'Press Start 2P';" class="botoes">
		<a href="{% url 'jogo:finalizar' %}"><button class="btn btn-default btn-finalizar" type="button"><span class="glyphicon glyphicon-floppy-disk"></span> Finalizar</button></a>
	</div>
	</div>
	
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

</body>
</html>

templates/jogo/game.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Camen San Diego - França</title>
	<link href="https://fonts.googleapis.com/css?family=Aldrich|Allerta+Stencil|Bangers|Barrio|Black+Ops+One|Bungee+Shade|Diplomata|Faster+One|Holtwood+One+SC|Monofett|New+Rocker|Pacifico|Press+Start+2P|Righteous|Sigmar+One" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


<style type="text/css">
body {
	font-family: 'Press Start 2P';
}

p {
	font-family: 'Press Start 2P';
	font-size: 14px;
}

.tudo {
	display: table;
}

.border {
	border: 5px solid #fff;
}

.rigth {
	float: left;
}

.imagem-wrapper {
    width: 40%;
    height: 544px;
    overflow: hidden;
    position: relative;
    float: left;
}

.conteudo {
	margin-left: 42%;
	height: 450px;
	padding: 10px;
}

.botoes {
	margin-top: 2%;
	margin-left: 42%;
}

.imagem {
    width: 800px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translateX(-50%) translateY(-50%);
}
	</style>
</head>
<body style="background-color: #141414;">
	<div style="display: inline-block;">
	<div style="color: #fff; text-align: center; font-family: 'Press Start 2P'; font-size: 11px; margin-bottom: 5px;" class="border">
		<h1>{{pais.nome}}</h1>
	</div>
	<div class="imagem-wrapper border">
		<img class="imagem" src="/media/{{pais.imagem_pais}}">
	</div>
	<div style="color: #fff; font-family: 'Press Start 2P';" class="conteudo border">
		<p>{{pais.descricao}}</p>
	</div>
	<div style="font-family: 'Press Start 2P';" class="botoes">
		<button class="btn btn-default" type="button" data-toggle="modal" data-target="#Testemunhas"><span class="glyphicon glyphicon-user"></span> Testemunhas</button>
		<button class="btn btn-default" type="button" data-toggle="modal" data-target="#Viajar"><i class="fas fa-plane-departure"></i> Viajar</button>
		<a href="{% url 'jogo:salvar' pais.pk %}"><button class="btn btn-default" type="button"><span class="glyphicon glyphicon-floppy-disk"></span> Salvar e <span class="glyphicon glyphicon-log-out"></span> Sair</button></a>
	</div>
	</div>

	<!-- Modal Viajar -->
	<div class="modal fade" id="Viajar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Para onde deseja viajar?</h4>
	      </div>
	      <div class="modal-body">
			<div class="row">
			  <div class="col-sm-6 col-md-4">
			    <div class="thumbnail">
			      <a href="/pais/{{pais.pais_um.pk}}"><img src="/media/{{pais.pais_um_imagem}}" alt="{{pais.pais_um.nome}}"></a>
			      <div class="caption" style="text-align: center;">
			        <a href="/pais/{{pais.pais_um.pk}}"><p>{{pais.pais_um.nome}}</p></a>
			      </div>
			    </div>
			  </div>
			  <div class="col-sm-6 col-md-4">
			    <div class="thumbnail">
			      <a href="/pais/{{pais.pais_dois.pk}}"><img src="/media/{{pais.pais_dois_imagem}}" alt="{{pais.pais_dois.nome}}"></a>
			      <div class="caption" style="text-align: center;">
			        <a href="/pais/{{pais.pais_dois.pk}}"><p>{{pais.pais_dois.nome}}</p></a>
			      </div>
			    </div>
			  </div>
			</div>
	      </div>
	      <div class="modal-footer">

	      </div>
	    </div>
	  </div>
	</div>

	<!-- Modal Testemunhas -->
	<div class="modal fade" id="Testemunhas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Testemunhas</h4>
	      </div>
	      <div class="modal-body">
			<div class="media">
			  <div class="media-left">
			      <img class="media-object" src="/media/{{pais.testemunha_um_imagem}}" alt="{{pais.testemunha_um_nome}}" width="100">
			  </div>
			  <div class="media-body">
			    <h4 class="media-heading">{{pais.testemunha_um_nome}}</h4>
			    {{pais.testemunha_um_fala}}
			  </div>
			</div>

			<div class="media">
			  <div class="media-left">
			      <img class="media-object" src="/media/{{pais.testemunha_dois_imagem}}" alt="{{pais.testemunha_dois_nome}}" width="100">
			  </div>
			  <div class="media-body">
			    <h4 class="media-heading">{{pais.testemunha_dois_nome}}</h4>
			    {{pais.testemunha_dois_fala}}
			  </div>
			</div>
	      </div>
	      <div class="modal-footer"></div>
	    </div>
	  </div>
	</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

</body>
</html>

templates/jogo/start.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Camen SanDiego</title>
	<link href="https://fonts.googleapis.com/css?family=Aldrich|Allerta+Stencil|Bangers|Barrio|Black+Ops+One|Bungee+Shade|Diplomata|Faster+One|Holtwood+One+SC|Monofett|New+Rocker|Pacifico|Press+Start+2P|Righteous|Sigmar+One" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


<style type="text/css">
body {
	font-family: 'Press Start 2P';
}

p {
	color: #fff;
	position: absolute;
	top: 15%;
}

.button-login {
	position: absolute;
	top: 80%;
}

.button-cadastro {
	position: absolute;
	top: 80%;
	left: 10%;
}

.button-nova {
	position: absolute;
	top: 80%;
}

.button-continuar {
	position: absolute;
	top: 80%;
	left: 18%;
}

.button-sair {
	position: absolute;
	top: 90%;
	left: 15%;
}

.erro {
	position: absolute;
	top: 25%;
}
</style>
</head>
<body style="background-image: url({% static 'images/carmen.jpg' %}); background-repeat: no-repeat; background-position: 30% 25%;">
	{% if request.user.is_authenticated %}
	<p>Bem vindo, agente {{ request.user.username }}! <br>Selecione uma das opções e divirta-se.</p>
	<a href="{% url 'jogo:partida' %}"><button class="btn btn-default button-nova" type="button"><i class="fas fa-plus"></i> Nova Partida</button></a>
	<a href="{% url 'jogo:continuar' %}"><button class="btn btn-default button-continuar" type="button"><i class="fas fa-gamepad"></i> Continuar Partida</button></a>
	<a href="{% url 'core:logout' %}"><button class="btn btn-danger button-sair" type="button"><i class="fa fa-sign-out-alt" aria-hidden="true"></i> Sair</button></a>
	{% if mensagem %}
	<p class="erro">{{mensagem}} <br> Para continuar uma partida você deve ter partidas salvas.</p>
	{% endif %}

	{% else %}
		<p>Bem vindo, ao jogo Carmen SanDiego. <br>Para começar, crie uma conta ou faça login!</p>
		<a href="{% url 'core:login' %}"><button class="btn btn-default button-login" type="button"><span class="glyphicon glyphicon-user"></span> Login</button></a>
		<a href="{% url 'core:cadastro' %}"><button class="btn btn-default button-cadastro" type="button"><i class="fas fa-plane-departure"></i> Cadastro</button></a>
	{% endif %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

</body>
</html>